# Generated by Django 4.1.2 on 2022-11-05 11:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('cse_Acess', models.BooleanField(default=False)),
                ('mec_Acess', models.BooleanField(default=False)),
                ('cce_Acess', models.BooleanField(default=False)),
                ('ece_Acess', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='spez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.department')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('cgpa_Req', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('phd_Req', models.BooleanField(default=False)),
                ('createdby', models.CharField(max_length=30)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.department')),
                ('spez_Req', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.spez')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('title', models.CharField(choices=[('1', 'Mrs.'), ('2', 'Mr.'), ('3', 'Dr.'), ('4', 'Ms.')], max_length=5)),
                ('father', models.CharField(max_length=40, null=True)),
                ('mother', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(choices=[('1', 'GEN'), ('2', 'SC'), ('3', 'ST'), ('4', 'OBC')], max_length=5)),
                ('Nationality', models.CharField(max_length=30)),
                ('qualifications', models.CharField(choices=[('1', 'B.A.'), ('2', 'B.Arch.'), ('3', 'BSc'), ('4', 'MSc'), ('5', 'B.Tech'), ('6', 'M.Tech'), ('7', 'PhD')], max_length=30)),
                ('cgpa', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('experiance', models.PositiveBigIntegerField(default=0)),
                ('citations', models.PositiveBigIntegerField(default=0)),
                ('publications', models.PositiveBigIntegerField(default=0)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('postal', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('mob_num', models.CharField(max_length=10)),
                ('hireScore', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('schedule', models.DateTimeField(null=True)),
                ('roundNum', models.PositiveSmallIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.job')),
                ('spez', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.spez')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
