# Generated by Django 4.1.2 on 2022-11-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='spez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.spez'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='spez_Req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.spez'),
        ),
        migrations.AlterField(
            model_name='spez',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.department'),
        ),
    ]
