# Generated by Django 4.1.2 on 2022-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cgpa_Req',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
