# Generated by Django 4.1.2 on 2022-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_job_cgpa_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cgpa_Req',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
