# Generated by Django 4.1.2 on 2022-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_job_cgpa_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='meet',
            field=models.URLField(default='www.placeholder.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='hireScore',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
